CREATE TABLE STOCK(
	idSERIAL INT NOT NULL PRIMARY KEY,
	COMPANY VARCHAR(255) NOT NULL,
	SNAP_DATE DATE NOT NULL,
	SNAP_TIME TIME NOT NULL,
	OPEN_PRICE DECIMAL(10,2),
	HIGH_PRICE DECIMAL(10,2),
	LOW_PRICE DECIMAL(10,2),
	CLOSE_PRICE DECIMAL(10,2),
	VOLUME DECIMAL(15,2)
);

SELECT COMPANY,

       AVG(OPENPRICE) + AVG(HIGHPRICE) + AVG(LOWPRICE) + AVG(CLOSEPRICE) AS CHECK1,

       AVG(VOLUME) AS CHECK2,

       COUNT(COMPANY) AS COUNT

  FROM STOCK

 GROUP BY COMPANY;